export const CUSTOMERS_INITIAL_DATA = [
  // AUTO Category
  { name: "PT. ADI", quantitySchedule: 16877, category: "AUTO" },
  { name: "PT. JONAN", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. KOITO", quantitySchedule: 20550, category: "AUTO" },
  { name: "PT. PHC", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. SIIX", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. MURAKAMI", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. YIMM", quantitySchedule: 400, category: "AUTO" },
  { name: "PT. SIIX TRADING", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. AHM", quantitySchedule: 6030, category: "AUTO" },
  { name: "PT. INS", quantitySchedule: 30500, category: "AUTO" },
  { name: "PT. HLI/MAS-I", quantitySchedule: 16400, category: "AUTO" },
  { name: "PT. MINA", quantitySchedule: 36900, category: "AUTO" },
  { name: "PT. ISE", quantitySchedule: 51300, category: "AUTO" },
  { name: "PT. STANLEY EXP", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. ICHIKOH", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. KATOLEC", quantitySchedule: 1800, category: "AUTO" },
  { name: "PT. MAPI", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. PTI", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. SHINSEI", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. YEID", quantitySchedule: 1875, category: "AUTO" },
  { name: "PT. HARTONO IT", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. CRAZE", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. TSA (TIGA SAKTI A)", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. AST", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. EPSON", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. KIYOKUNI", quantitySchedule: 27500, category: "AUTO" },
  { name: "PT. KIYOKUNI 2", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. KIYOKUNI TECH", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. MURAMOTO", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. PATCO CIKARANG", quantitySchedule: 49500, category: "AUTO" },
  { name: "PT. PARAGON", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. TOYOPLAST", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. VST", quantitySchedule: 0, category: "AUTO" },
  { name: "PT. SMT", quantitySchedule: 0, category: "AUTO" },

  // AUDIO Category
  { name: "PT. PMI AC", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. PMI AUDIO", quantitySchedule: 200, category: "AUDIO" },
  { name: "PT. PMI IAQ", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. PMI RF", quantitySchedule: 2090, category: "AUDIO" },
  { name: "PT. PMI WM", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. SBE", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. YASUNAGA", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. YMMA", quantitySchedule: 24450, category: "AUDIO" },
  { name: "PT. NIKATSU", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. BANDO", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. KATOLEC AUDIO", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. MITRA METAL", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. PENSTONE", quantitySchedule: 6005, category: "AUDIO" },
  { name: "PT. HAIER", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. ITEC", quantitySchedule: 32857, category: "AUDIO" },
  { name: "PT. KAWAI", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. SHARP WM", quantitySchedule: 12300, category: "AUDIO" },
  { name: "PT. YEMI", quantitySchedule: 14400, category: "AUDIO" },
  { name: "PT. HONORIS", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. ATSUMITEC", quantitySchedule: 3240, category: "AUDIO" },
  { name: "PT. ARGATAMA", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. OMRON", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. YIFANG", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. GUNA ALPHA GLOBAL", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. PHC AUDIO", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. SHARP (TV)", quantitySchedule: 0, category: "AUDIO" },
  { name: "PT. DAIKIN", quantitySchedule: 1600, category: "AUDIO" },
];
